<center><font size="+4">ICT 2025/2026</font></center>
<center><font size="+2">Master of Science in Innovation Management – MAIN</font></center>
<center><font size="+2">Sant'Anna School of Advanced Studies, Pisa, Italy</font></center>
<center><img src="https://github.com/EMbeDS-education/ComputingDataAnalysisModeling20252026/raw/main/PDAI/jupyter/jupyterNotebooks/images/sssaLEMBEDSdtu.png" width="900" alt="L'EMbeDS"></center>

<center><font size="+2">Course responsible</font></center>
<center><font size="+2">Andrea Vandin a.vandin@santannapisa.it</font></center>

<center><font size="+2">co-Lecturer</font></center>
<center><font size="+2">Paolo Ferragina p.ferragina@santannapisa.it</font></center>
<center><font size="+2">co-Lecturer</font></center>
<center><font size="+2">Anna Monreale anna.monreale@unipi.it</font></center>

---

<center><font size="+4">Assignments for</font></center>
<center><font size="+4">Lecture: Numpy</font></center>

---


In [ ]:
#@title RUN, BUT DO NOT MODIFY
url = 'https://raw.githubusercontent.com/EMbeDS-education/ComputingDataAnalysisModeling20252026/main/ICT/jupyter/jupyterNotebooks/assignments/auto_testing.py'
url_github_repo="https://github.com/EMbeDS-education/ComputingDataAnalysisModeling20252026/raw/main/ICT/"

import urllib.request
from pathlib import Path

urllib.request.urlretrieve(url,Path(url).name)

#%reload_ext autoreload
#%autoreload 2
from auto_testing import *

#%pip install numpy
#import numpy as np

# Assignment 01.01: Play with vectorized arithmetics and broadcasting
## Statement

You are given a program that
- Reads and prints 2 lists of integers `l1`, `l2`
  - __This is already done for you. Do no change the corresponding code__
- Using numpy, complete the program such that it
  - Loads the two lists in arrays `data1` and `data2`
  - `Print`s `data1`
  - `Print`s `data2`  
  - Computes and `print`s the element-wise sum of `data1` and `data2`, and stores it it `data_sum`
  - Reshapes and `print`s `data_sum` in a 2x2 matrix `matrix`
  - Computes and `print`s the element-wise _product times 10_ of `matrix`, storing it in `matrix_times_10`
  - Removes from `matrix_times_10` half the original value `matrix` and `print`s it

## Example input #1

```
0,1,2,3
```

```
4,5,6,7
```

## Example output #1

```
[0, 1, 2, 3]
[4, 5, 6, 7]
[ 4  6  8 10]
[[ 4  6]
 [ 8 10]]
[[ 40  60]
 [ 80 100]]
[[38. 57.]
 [76. 95.]]
```


## Write your solution here


*   Do not change the first line (`def ...():`)
*   Maintain the given indentation
*   You can run some tests by yourself by decommenting the last line



In [ ]:
def asgn01_01Play_With_Arith():
     # This program reads two lists from input given in format: 1,2,3
    l1_str=input()
    l1 = [int(i) for i in l1_str.split(',')]

    l2_str=input()
    l2 = [int(i) for i in l2_str.split(',')]

    print(l1)
    print(l2)

    # Add your solution here

#You can test independently your solution by executing the following line
#asgn01_01Play_With_Arith()
#Sample input
#0,1,2,3

## Run the following cells to perform the provided tests

In [ ]:
#@title RUN, BUT DO NOT MODIFY
from IPython.display import display, Markdown
from auto_testing import *

inputs=[["0,1,2,3","4,5,6,7"],\
        ["14,15,16,17","23,24,25,26"],\
        ["0,0,0,0","0,0,0,0"]
       ]
expected_outputs=[ ["[0, 1, 2, 3]","[4, 5, 6, 7]","[0 1 2 3]","[4 5 6 7]","[ 4  6  8 10]","[[ 4  6]"," [ 8 10]]",\
                                    "[[ 40  60]"," [ 80 100]]","[[38. 57.]"," [76. 95.]]"],\
                   ["[14, 15, 16, 17]","[23, 24, 25, 26]","[14 15 16 17]","[23 24 25 26]","[37 39 41 43]","[[37 39]"," [41 43]]","[[370 390]"," [410 430]]","[[351.5 370.5]"," [389.5 408.5]]"],\
                   ["[0, 0, 0, 0]","[0, 0, 0, 0]","[0 0 0 0]","[0 0 0 0]","[0 0 0 0]","[[0 0]"," [0 0]]","[[0 0]"," [0 0]]","[[0. 0.]"," [0. 0.]]"]
                 ]



for k in range(len(inputs)):
  display(Markdown(f'{k+1}. TEST {inputs[k]} = {",".join(expected_outputs[k])}'))
  print('-'*60)
  run_and_test(inputs[k],expected_outputs[k],asgn01_01Play_With_Arith)

# Assignment 01.02: Play with slices
## Statement

You are given a program that
- Reads and prints 1 list of integers `l1`
  - __This is already done for you. Do no change the corresponding code__
- Using numpy, complete the program such that it
  - Loads the list in array `data1`, and `print`s it
  - Computes and `print`s a slice of `data1` containing the first 8 elements
  - Computes and `print`s a slice of `data1` containing all but the last 3 elements
  - Computes and `print`s a slice of `data1` containing only the last 3 elements  
  - Computes and `print`s a slice of `data1` dropping the first 3 elements and the last 2

## Example input #1

```
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
```

## Example output #1

```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[0 1 2 3 4 5 6 7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[13 14 15]
[ 3  4  5  6  7  8  9 10 11 12 13]
```


## Write your solution here


*   Do not change the first line (`def ...():`)
*   Maintain the given indentation
*   You can run some tests by yourself by decommenting the last line



In [ ]:
def asgn01_02Play_With_Slices():
     # This program reads a list from input given in format: 1,2,3
    l1_str=input()
    l1 = [int(i) for i in l1_str.replace(" ", "").split(',')]
    print(l1)
    # Add your solution here

#You can test independently your solution by executing the following line
#asgn01_02Play_With_Slices()
#Sample input
#0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

## Run the following cells to perform the provided tests

In [ ]:
#@title RUN, BUT DO NOT MODIFY

from auto_testing import *
from IPython.display import display, Markdown

inputs=[["0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"],
        ["0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30"]
       ]
expected_outputs=[ ["[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]","[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]","[0 1 2 3 4 5 6 7]","[ 0  1  2  3  4  5  6  7  8  9 10 11 12]","[13 14 15]","[ 3  4  5  6  7  8  9 10 11 12 13]"],
                  ["[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]","[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]","[ 0  2  4  6  8 10 12 14]","[ 0  2  4  6  8 10 12 14 16 18 20 22 24]","[26 28 30]","[ 6  8 10 12 14 16 18 20 22 24 26]"]
                 ]



for k in range(len(inputs)):
  display(Markdown(f'{k+1}. TEST {inputs[k]} = {",".join(expected_outputs[k])}'))
  print('-'*60)
  run_and_test(inputs[k],expected_outputs[k],asgn01_02Play_With_Slices)

# Assignment 01.03: Play with slices 2
## Statement

You are given a program that
- Reads and prints 1 list of integers `l1`
  - __This is already done for you. Do no change the corresponding code__
- Using numpy, complete the program such that it
  - Loads the list in array `data1`, and `print`s it
  - Reshapes and `print`s `data1` in a 4x4 matrix `matrix`
  - Computes and `print`s a slice of `matrix` selecting only the first row
  - Computes and `print`s a slice of `matrix` selecting only the first column
  - Computes and `print`s a slice of `matrix` selecting the 4 elements in the top-left
  - Computes and `print`s a slice of `matrix` selecting the 4 elements in the bottom-left  
  - Computes and `print`s a slice of `matrix` selecting the 4 elements in the middle of the matrix

## Example input #1

```
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
```

## Example output #1

```
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[ 0  4  8 12]
[[0 1]
 [4 5]]
[[ 8  9]
 [12 13]]
[[ 5  6]
 [ 9 10]]
```


## Write your solution here


*   Do not change the first line (`def ...():`)
*   Maintain the given indentation
*   You can run some tests by yourself by decommenting the last line



In [ ]:
def asgn01_03Play_With_Slices():
     # This program reads a list from input given in format: 1,2,3
    l1_str=input()
    l1 = [int(i) for i in l1_str.split(',')]
    print(l1)
    # Add your solution here



#You can test independently your solution by executing the following line
#asgn01_03Play_With_Slices()
#Sample input
#0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

## Run the following cells to perform the provided tests

In [ ]:
#@title RUN, BUT DO NOT MODIFY
from IPython.display import display, Markdown
from auto_testing import *

inputs=[["0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"],\
        ["0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30"]
       ]
expected_outputs=[ ["[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]","[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]","[[ 0  1  2  3]"," [ 4  5  6  7]"," [ 8  9 10 11]"," [12 13 14 15]]","[0 1 2 3]","[ 0  4  8 12]","[[0 1]"," [4 5]]","[[ 8  9]"," [12 13]]","[[ 5  6]"," [ 9 10]]"],
                   ["[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]","[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]","[[ 0  2  4  6]"," [ 8 10 12 14]"," [16 18 20 22]"," [24 26 28 30]]","[0 2 4 6]","[ 0  8 16 24]","[[ 0  2]"," [ 8 10]]","[[16 18]"," [24 26]]","[[10 12]"," [18 20]]"]
                 ]



for k in range(len(inputs)):
  display(Markdown(f'{k+1}. TEST {inputs[k]} = {",".join(expected_outputs[k])}'))
  print('-'*60)
  run_and_test(inputs[k],expected_outputs[k],asgn01_03Play_With_Slices)